### ISSUE TITLE
Possible license violation

### ISSUE THREAD

**Issue by ZanderBrown** [pali/libopenaptx#11]
`libopenaptx` provides a [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) file, assuming this file is distributed under the same terms as the rest of `libopenaptx`  this breaks `libopenaptx` license provisions around freedesktop projects (or rather could cause users to unintentionally break them)

This can be resolved with the following patch

```
diff --git a/Makefile b/Makefile
index fb41ab9..ce98e71 100644
--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,6 @@ RM = rm -f
 CP = cp -a
 LNS = ln -sf
 MKDIR = mkdir -p
-PRINTF = printf
 
 CFLAGS = -W -Wall -O3
 LDFLAGS = -s
@@ -35,7 +34,6 @@ PREFIX = /usr/local
 BINDIR = bin
 LIBDIR = lib
 INCDIR = include
-PKGDIR = $(LIBDIR)/pkgconfig
 
 NAME = openaptx
 MAJOR = 0
@@ -46,7 +44,6 @@ LIBNAME = lib$(NAME).so
 SONAME = $(LIBNAME).$(MAJOR)
 SOFILENAME = $(SONAME).$(MINOR).$(PATCH)
 ANAME = lib$(NAME).a
-PCNAME = lib$(NAME).pc
 
 UTILITIES = $(NAME)enc $(NAME)dec
 STATIC_UTILITIES = $(NAME)enc.static $(NAME)dec.static
@@ -73,15 +70,11 @@ install: default
 	$(MKDIR) $(DESTDIR)$(PREFIX)/$(INCDIR)
 	$(CP) $(HEADERS) $(DESTDIR)$(PREFIX)/$(INCDIR)
 	$(MKDIR) $(DESTDIR)$(PREFIX)/$(PKGDIR)
-	$(PRINTF) 'prefix=%s\nexec_prefix=$${prefix}\nlibdir=$${exec_prefix}/%s\nincludedir=$${prefix}/%s\n\n' $(PREFIX) $(LIBDIR) $(INCDIR) > $(DESTDIR)$(PREFIX)/$(PKGDIR)/$(PCNAME)
-	$(PRINTF) 'Name: lib%s\nDescription: Open Source aptX codec library\nVersion: %u.%u.%u\n' $(NAME) $(MAJOR) $(MINOR) $(PATCH) >> $(DESTDIR)$(PREFIX)/$(PKGDIR)/$(PCNAME)
-	$(PRINTF) 'Libs: -Wl,-rpath=$${libdir} -L$${libdir} -l%s\nCflags: -I$${includedir}\n' $(NAME) >> $(DESTDIR)$(PREFIX)/$(PKGDIR)/$(PCNAME)
 
 uninstall:
 	for f in $(SOFILENAME) $(SONAME) $(LIBNAME) $(ANAME); do $(RM) $(DESTDIR)$(PREFIX)/$(LIBDIR)/$$f; done
 	for f in $(UTILITIES); do $(RM) $(DESTDIR)$(PREFIX)/$(BINDIR)/$$f; done
 	for f in $(HEADERS); do $(RM) $(DESTDIR)$(PREFIX)/$(INCDIR)/$$f; done
-	$(RM) $(DESTDIR)$(PREFIX)/$(PKGDIR)/$(PCNAME)
 
 $(UTILITIES): $(LIBNAME)
```

Unfortunately this patch cannot be contributed, even if I wanted to, since `libopenaptx`'s license bars me from contributing

Additionally it should probably be made clear that uses of `libopenaptx` wishing to use glibc should use a version prior to at least https://github.com/bminor/glibc/commit/a64afc225240b2b27129ccfb0516d7c958b98040 (though I suspect to collabora involvement goes back further)

**Comment by ZanderBrown** [comment]
This issue is a license violation, closing

**Comment by pali** [comment]
See https://github.com/pali/libopenaptx/issues/12

**Comment by ZanderBrown** [comment]
So in effect the comments of https://github.com/pali/libopenaptx/commit/811bc18586d634042618d633727ac0281d4170b8 are null and void?

**Comment by pali** [comment]
No, it is not. Read it again. Project licence was upgraded to GPLv3 to be compatible with projects under Apache Licence 2.0.

**Comment by ZanderBrown** [comment]
You have provided various provisions attempting to block people such as myself from using `libopenaptx` however in #12 you seem to have stated these provisions are unenforceable - and possibly even conflict with GPL - so it would seem to me they are, for all practical purposes, null and void

**Comment by pali** [comment]
If your only purpose is to send rubbishy and pointless patches and issues for this project then sorry, I'm not going to discuss with you. Patch in this issue including your comments is just such spam example.

**Comment by ZanderBrown** [comment]
It's actually a fairly serious concern, you either have or haven't blocked the use of `libopenaptx` with projects related to collabora/xdg - which would include pkg-config

**Comment by pali** [comment]
Sorry, that is not my problem. They had more than half of year of time to resolve this issue. But that they did anything and just blaming me and other people. And I do not understand why you are reporting this issue to this project. It is problem in freedesktop, so once they fix it, we can continue here.

**Comment by ZanderBrown** [comment]
> this library and any other project which uses this library must not
be used or distributed in any Freedesktop or Collabora project, application or
library, either in source code, loaded or linked at compile time or at runtime
either directly or transitionally throw additional wrapper library or in any
other similar form.

You provide a pkg-config file, as pkg-config is a freedesktop project anyone using that file would be breaking your terms

Aditionally Collabora have contributed to glibc and the kernel violating "loaded or linked at compile time or at runtime
either directly or transitionally"

This particular problem cannot be resolved elsewhere as it is you who set these terms

**Comment by pali** [comment]
Could you please stop spamming this issue tracker? I have already expressed that I'm not interested in your rubbishy and pointless patches.

To your previous comment, this repository does not contain any pkg config application nor any link to such application.

And if you are unhappy that `install` target generates some text files which you can use by your pkg config application, then just do not use your pkg config application. Or do not use `install` target.

And if you do not like this library or you cannot use it then solution is simple: do not use it. I'm not forcing you to use it.

This is my last comment in this nonsense topic.

**Comment by ZanderBrown** [comment]
> then just do not use your pkg-config application

This is entirely unreasonable, this would prevent people from engaging in any development on systems where `libopenaptx` is installed (pkg-config being used in meson, cmake, autotools and even makefiles)

Given there is no compliant way to use that file (and it's existance effectively nukes pkg-config) it seems entirely sensible for it to be dropped

**Comment by PranavBhattarai** [comment]
I landed here when someone named "Old Nobody" [comments](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1270067-pulseaudio-15-released-with-bluetooth-improvements-better-hardware-support) the author. 

I have one reaction: 'Oh boy with a face plam'.

Confused with one question though: Why its even GPL3 when....

**Comment by msva** [comment]
@ZanderBrown actually, `pkgconfig` is pretty dead (last release is 4 years ago, contains many bugs and so on).
Soe distributions are already switched to [pkgconf](https://git.sr.ht/~kaniini/pkgconf) (say, Gentoo). Others are welcome to follow.

So, actually, there is no issue you mention.
As @pali said, just don't use `pkgconfig` (since it is dead already)

**Comment by kiefernforst** [comment]
@ZanderBrown Please toggle your activity to public.
