### ISSUE TITLE
Please provide links or citations for README claims

### ISSUE THREAD

**Issue by falkTX** [pali/libopenaptx#13]
Hi.
Just reading through the readme, a lot of big claims are being made.
For example:

> Freedesktop and Collabora projects are continuously abusing and violating license of this project

There are no references, links, citations, anything for proving that it is indeed the case.
Understandably raw text files can't provide inline links, so please consider providing links like this [1] or this [2].

[1] some well intended link
[2] another relevant link

Thanks!

**Comment by pali** [comment]
It was mentioned more times by more people on freedesktop platforms. But due to their censorship, all posts were deleted and they claimed that nothing like that happened and that they can do anything. So there are no active links anymore. So for links you would have to ask them, but beware that they can ban anybody who will start this discussion again.

I'm not going to participate in this discussion 6 month after again.

**Comment by falkTX** [comment]
then use webarchive for those? as it is, it seems like it is all made up by you...

**Comment by ZanderBrown** [comment]
I would also like like to see some citations

**Comment by pali** [comment]
Just one example. Compare for example current version of pulseaudio file https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/modules/bluetooth/a2dp-codec-aptx-gst.c with files from this merge request https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227 or with some older version from https://patchwork.freedesktop.org/series/55117/ (or from https://patchwork.freedesktop.org/patch/361589/?series=55117&rev=124) You can also check that e.g. function 
decode_buffer has even same comments. And you can think what is source of that code work. That freedesktop people claims that it is their own and that they have written it. It was mentioned more times on freedesktop portals but all these disucssions are disallowed by CoC and admins and they have removed all discussions about it.

I'm not sure if there is webarchive for it. And I do not want to spend more times on this topic.

**Comment by falkTX** [comment]
So you submitted that code as PR yourself, and are complaining they are using that same exact code?

There were clashes and bad decisions and bad actions in there, but seems valid to reuse code that was submitted as PR.

**Comment by pali** [comment]
Valid is not removing authorship and copyright and claiming that it was fully written by freedesktop people. And saying that they have legal rights to do this. Sorry I'm not going to enter into this discussion again, I'm not interested in it again.

**Comment by Hi-Angel** [comment]
> merge request https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227

Wow, that is a really sad story. I cursory read through it *(that's a very long thread, with 149 participants at the time it got locked)*. Well, [at least one PA maintainer apologized](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227#note_726012) for what happened there. Also, Daniel Stone, the current Collabora Graphics lead, [seems to be on your side](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227#note_728234), as well as many other peoples there.

Idk what to say. Probably, c'est la vie: in general, sometimes there are bad people, [but even more often there are… let's say, not very smart people](https://en.wikipedia.org/wiki/Hanlon%27s_razor). I don't know if any of that was the case there, however I'd like to say that it could be useful not to generalize. You have many supporters both from community and even from people on Freedesktop. The Pulseaudio maintainers aren't "everyone". Those were very sad events, and I hope all participants feel that. But that happens, just avoid the people you know to be problematic, and in case of really big problems try to turn to a wider community via reddit or similar places.

> Compare for example current version of pulseaudio file https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/modules/bluetooth/a2dp-codec-aptx-gst.c with files from this merge request

I think I understand what happened there. You see, the community I mentioned, they wanted your work. You created quite a bit of momentum there. After you left *(for a reason)*, people tried contacting you but failed at it. [Then someone had to re-do your work, and they based that off your patches](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227#note_736961). You see, in open-source there are sometimes abandoned patches that people still want. This means someone has to take over such patches. That gives a gray zone on who the authorship should be contributed to, especially given that git only allows one author. I'd personally say, that depends on how much of new work has to be done on top of the older changes. Like, if it's a complete rewrite, I think it's fair for the developer who took over the patches to take the authorship as well. When I look at the [MR that was based off your changes](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/440), it does look like a lot of work, so maybe that's what happened there.

**Comment by rubyFeedback** [comment]
IMO, aside from the snail-pace speed of the pulseaudio maintainers, the even more troubling aspect is how gitlab censors discussions or stakeholders (e. g. who wrote code).

Hi-Angel wrote:

> After you left (for a reason), people tried contacting you but failed at it.

I can not speak for pali, but I have tons of emails that are not answered. The reason is that my workflow
is so strange for others to understand but not easy to adapt, so I will not be able to read emails or 
participate in discussions. I don't know if this is the case with pali, but I can absolutely relate to that.
It's not even any ill intent - my workflow just so happens to be very "off" the norm. I am also prone to
be distracted quite easily. :P

As for pulseaudio - perhaps pipewire will eventually assimilate all of the functionality rather than 
have to act as a proxy for pulseaudio; pipewire seems to have more momentum than the
snail-pace pulseaudio anyway. :P

**Comment by pali** [comment]
> After you left (for a reason), people tried contacting you but failed at it.

This is one big lie presented by Freedesktop and Collabora people... See: https://github.com/pali/hsphfpd-prototype/issues/11#issuecomment-775312445 Freedesktop and Collabora people were asked many times (not only by me) to explain their activities and to stop doing it, but they refused and also refused to explain anything or even to communicate.

They just wanted my code without my attribution / copyright. They even started preparing this dirty job / plan prior all this happened. See e.g. https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227#note_728200 for recap. And when I rejected it they started harassment on me via private channels, they that want it and will do it.

Note that on patchwork is just old version of my patches. If you want to compare, look for latest version of patches which are (or rather were) on https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/288 and https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227

**Comment by mirh** [comment]
> And when I rejected it they started harassment on me via private channels, they that want it and will do it.

They claim you also banned them from a public channel like this one, though.... Where everybody could have seen and confirmed any swindle.

**Comment by pali** [comment]
Yes, I have wrote into it also into README file that due to their behavior, they cannot post into my personal projects any issue or feature request. What do you they think, if they ban me from their project that I allow them to post patches/issues into my projects? They had more than 6 months to explain or communicate, but they did not wanted. If they really wanted to communicate with me they would obviously do not ban me or disallow me to write any response.

**Comment by mirh** [comment]
That may be all fine and dandy, but if you blocked them in every single location of this earth I'm not sure how you expect the "communication" to happen like at all, even if they magically got their shit together tomorrow. 

Also, "tit for tat" makes no sense. If they are thieves, then on top of them supposedly being too dumb to make any contributions, you aren't any better in banning them for flame reasons (in fact it could be argued you are doing even worse, given you acted *preemptively* without even the slightest shadow of spam, disrespect, or even simple "time waste" here)

**Comment by KilianHanich** [comment]
> I think it's fair for the developer who took over the patches to take the authorship as well.

Depending on the origin country, that doesn't actually work. For example in Germany Copyright is not transferable.
This actually leads to the situation that Germans can't contribute to projects which want that. I once talked with a co-worker who wanted to contribute to GCC (I don't think they require this these days, but they were back then), but when he mentioned this he was straight up blocked.

**Comment by KilianHanich** [comment]
Short question: If you are sure to be in the right, why don't you go the legal way, if needed via a lawsuit?
Copyright is for Open Source and developers in general one of the most important things and we MUST enforce it. If needed against other projects who think they can do what they want.
