### ISSUE TITLE
Meaning of size

### ISSUE THREAD

**Issue by pschatzmann** [pali/libopenaptx#16]
I tried to use your library but so far w/o success. I see potentially 3 different sources of trouble
- I am completely confused about the meaning of input size and output size in your aptx_encode and your aptx_decode_sync methods. Is it in bytes, in 24 bit samples or in number of 24 stereo samples.

I am  currently feeding the encoder with 4 raw 24bit signed stereo samples: thats in total 8 samples or 24 bytes. So would the input_size be 24 ?

Same question on the aptx_decode_sync() where I get the written as result. Is this in bytes or 24bit samples?

- I am note sure about the endiannes requirements of your library

I am using a little endian system, so I assume that I don't have to do any conversion.

- I am not sure if I handle the 24 to 16 and 16 bit to 24 bit conversion correctly.

**Comment by pali** [comment]
> I tried to use your library but so far w/o success. I see potentially 3 different sources of trouble
> 
> * I am completely confused about the meaning of input size and output size in your aptx_encode and your aptx_decode_sync methods. Is it in bytes, in 24 bit samples or in number of 24 stereo samples ?

Parameters named _size_ are always in bytes.

> * I am note sure about the endiannes requirements of your library

Library is endian neutral and should work on systems with any endianity. Buffer with raw audio samples are always in little endian format (also on big endian system).

> * I am not sure if I handle the 24 to 16 and 16 bit to 24 bit conversion correctly.

24bit to 16bit conversion is loosy, so you should not do it. If your input is 16-bit then simple bit shift samples and put zeros to the least meaningful bits.

**Comment by pschatzmann** [comment]
Ah, much better. The encoding and decoding of a sine wave is now giving the expected result
![Screen Shot 2022-05-07 at 15 56 53](https://user-images.githubusercontent.com/2078916/167257495-f48c4c38-7465-456e-b64a-9c3ca4815788.png)
:
