### ISSUE TITLE
Add pkg-config file

### ISSUE THREAD

**Issue by Keruspe** [pali/libopenaptx#2]
This helps integrating the library as a dependency in build systems

**Comment by pali** [comment]
Hi! What is the purpose or requirement of having pkg-config file? This library is indented to not have any C compile flags, nor any link flags.

**Comment by Keruspe** [comment]
You can easily require for example "libopenaptx >= 0.1.0" without having to manually look for new symbols added in v0.1.0 with code snippets, for example

**Comment by pali** [comment]
Ok. I thought that it is easier to add `#ifdef` version check into code and avoid usage of configure system... But if you rather have version check externally without need to write C code via pkg-config I would add Makefile rule to install simple pkg-config file in new libopenaptx version.

**Comment by pali** [comment]
Hello! A new release 0.2.0 of libopenaptx now generates pkg-config file during make install phase.
