### ISSUE TITLE
Doesn't build on recent Fedora

### ISSUE THREAD

**Issue by ocrete** [pali/libopenaptx#8]
Because the Makefile seems to insist on building the static library, it doesn't work on Fedora because it can't find "-lc". 

```
libopenaptx $ make
c99 -W -Wall -O3 -s -static -o openaptxenc.static openaptxenc.o libopenaptx.a
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [Makefile:90: openaptxenc.static] Error 1
```

I suggest moving the static library out of the *all* target and removing it as a dependency from the *install* target.

**Comment by ocrete** [comment]
I mean't static binaries obviously.

**Comment by pali** [comment]
This is bizarre. Your compiler on Fedora really does not support `-static` flag for producing statically linked executables? Or is not it just issue that you have not installed _full_ compiler support files?

**Comment by pali** [comment]
I guess you need glibc-static package.

**Comment by pali** [comment]
I see that static built binaries are not installed by default, but there is dependency install on it. I will modify and fix it.

**Comment by pali** [comment]
Should be fixed now in git.

**Comment by ocrete** [comment]
You have to remove `$(STATIC_UTILITIES)` the BUILD too.. as this is what "all" depends on.. so that one can do "make && sudo make install"

**Comment by pali** [comment]
Well, technically target 'all' should build all binaries available for project. Not just some. I will think about it more...

**Comment by pali** [comment]
Now by default are built only binaries which are going to be installed. So this issue should be fixed in git.

**Comment by pali** [comment]
@ocrete: Can you check if it is fixed for you now?

**Comment by pali** [comment]
Ok, I guess it is fixed, closing.

**Comment by ocrete** [comment]
Thanks, I can confirm this works (I stay away from the compuer for the weekends!)
